USE ROLE ACCOUNTADMIN;

USE WAREHOUSE COMPUTE_WH;

USE SCHEMA MYDB.MYSCHEMA;

CREATE OR REPLACE TABLE STUDENT (
    ID INTEGER,
    NAME VARCHAR(50),
    AGE INTEGER,
    MARKS INTEGER
);

--CREATE A NAMED STAGE
CREATE OR REPLACE STAGE STUDENT_STAGE;

LIST @STUDENT_STAGE;

--LOADING THE DATA INTO TABLE FROM STAGE (STUDENT)
COPY INTO STUDENT 
FROM @STUDENT_STAGE
FILE_FORMAT = (TYPE = 'CSV', SKIP_HEADER =1);

SELECT * FROM STUDENT;

--TRUNCATE THE TABLE
TRUNCATE TABLE STUDENT;

--CREATE A CSV FORMAT
CREATE OR REPLACE FILE FORMAT CSV_FORMAT
TYPE = 'CSV'
FIELD_DELIMITER = ','
RECORD_DELIMITER = '\n'
SKIP_HEADER = 1;

--COPY IT INTO THE TABLE
COPY INTO STUDENT
FROM @STUDENT_STAGE
FILE_FORMAT = (FORMAT_NAME = CSV_FORMAT);

--CREATE A JSON FILE
CREATE OR REPLACE FILE FORMAT JSON_FORMAT
TYPE = 'JSON';



--FOR THIS TO WORK WE NEED TO HAVE A JSON FILE IN OUR STAGE AND NOT THE CSV FILE RIGHT NOW I HAVE A CSV SO THIS DOES NMOT WORK
-- COPY INTO STUDENT
-- FROM @STUDENT_STAGE
-- FILE_FORMAT = (FORMAT_NAME = JSON_FORMAT);

SHOW FILE FORMATS;