USE ROLE ACCOUNTADMIN;

USE WAREHOUSE COMPUTE_WH;

USE SCHEMA MYDB.MYSCHEMA;

CREATE OR REPLACE TABLE EVENT(
    EVENT VARIANT
);

CREATE OR REPLACE STORAGE INTEGRATION S3_snowpipe_int
    TYPE = EXTERNAL_STAGE
    STORAGE_PROVIDER = 'S3'
    ENABLED = TRUE
    STORAGE_AWS_ROLE_ARN = 'arn:aws:iam::249173798438:role/snowpiperole'
    STORAGE_ALLOWED_LOCATIONS = ('s3://first-snowflake1-bucket/EVENT/');

DESCRIBE INTEGRATION S3_snowpipe_int;

CREATE OR REPLACE FILE FORMAT MY_JSON_FORMAT
    TYPE = 'JSON';

CREATE OR REPLACE STAGE snowpipe_stage
    STORAGE_INTEGRATION = S3_snowpipe_int
    URL = 's3://first-snowflake1-bucket/EVENT/'
    FILE_FORMAT = MY_JSON_FORMAT;

LIST @snowpipe_stage;

CREATE OR REPLACE PIPE S3_PIPE
    auto_ingest = TRUE AS
    COPY INTO EVENT
    FROM @SNOWPIPE_STAGE
    FILE_FORMAT = (FORMAT_NAME = MY_JSON_FORMAT);

SELECT SYSTEM$PIPE_STATUS('S3_PIPE');

SHOW PIPES;

Select * FROM EVENT;

