USE ROLE ACCOUNTADMIN;

USE WAREHOUSE COMPPUTE_WH;

USE SCHEMA MYDB.MYSCHEMA;

CREATE OR REPLACE TABLE CUSTOMER(
    ID INTEGER,
    NAME VARCHAR(50),
    AGE INTEGER,
    STATE VARCHAR(50)
);

-- TABLE STAGE
LIST @%CUSTOMER;

-- USER STAGE
LIST @~;

-- NAMED STAGE
CREATE OR REPLACE STAGE CUSTOMER_STAGE;

LIST @CUSTOMER_STAGE;

--DELETING ALL THE RECORDS THAT IS CURRENTLY ON THE CUSTOMER
TRUNCATE TABLE CUSTOMER;

--COPY THE FILES FROM THE CSV INTO THE CUSTOMER TABLE
COPY INTO CUSTOMER
FROM @CUSTOMER_STAGE
FILE_FORMAT = (TYPE = 'CSV' SKIP_HEADER = 1);

SELECT * FROM CUSTOMER; 
