USE ROLE ACCOUNTADMIN;

USE WAREHOUSE COMPUTE_WH;

USE SCHEMA MYDB.MYSCHEMA;

CREATE OR REPLACE TABLE DROP_TABLE(
    ID INT,
    NAME VARCHAR
);

INSERT INTO DROP_TABLE VALUES
    (1, 'John'),
    (2, 'SAM'),
    (3, 'ELAN'),
    (4, 'MARK');

DELETE FROM DROP_TABLE WHERE ID = 1;

SELECT * FROM DROP_TABLE AT (OFFSET => -60*2;

SELECT * FROM DROP_TABLE AT (TIMESTAMP => '2026-07-18 18:44:59.516 -0700'::timestamp_tz);

SELECT * FROM DROP_TABLE BEFORE(STATEMENT => '01c5cd89-0306-fbad-000f-167a0034d95e');

SHOW TABLES;


CREATE OR REPLACE TABLE DROP_TABLE_CLONE AS 
SELECT * FROM DROP_TABLE BEFORE(STATEMENT => '01c5cd89-0306-fbad-000f-167a0034d95e');

TRUNCATE TABLE DROP_TABLE;

INSERT INTO DROP_TABLE 
SELECT * FROM DROP_TABLE_CLONE;

DROP TABLE DROP_TABLE_CLONE;
    
SELECT * FROM DROP_TABLE;

DROP TABLE DROP_TABLE;

UNDROP TABLE DROP_TABLE;


-------Cloning
USE ROLE ACCOUNTADMIN;

USE WAREHOUSE COMPUTE_WH;

USE SCHEMA MYDB.MYSCHEMA;

CREATE OR REPLACE DATABASE test_mydb
CLONE mydb;

DROP DATABASE test_mydb;