USE ROLE accountadmin;

USE WAREHOUSE COMPUTE_WH;

USE SCHEMA MYDB.MYSCHEMA;

CREATE OR REPLACE TABLE PERMANENT_TABLE (
    ID INT,
    NAME STRING
);

ALTER TABLE PERMANENT_TABLE SET DATA_RETENTION_TIME_IN_DAYS = 90;

CREATE OR REPLACE TRANSIENT TABLE TRANSIENT_TABLE(
    ID INT,
    NAME STRING
);

INSERT INTO TRANSIENT_TABLE(ID, NAME) VALUES
(1,'ROBOT'),
(2,'TEDDY BEAR');

SELECT * FROM TRANSIENT_TABLE;

DELETE FROM TRANSIENT_TABLE WHERE ID = 2;


SELECT * FROM TRANSIENT_TABLE BEFORE (STATEMENT => '01c56c7a-0306-42c2-000f-167a0007d71e');

SELECT * FROM TRANSIENT_TABLE AT (OFFSET => -15);

CREATE OR REPLACE TEMPORARY TABLE TEMPORARY_TABLE(
    ID INT,
    NAME STRING
);


SHOW TABLES;

CREATE OR REPLACE TABLE EMPLOYEES(
    ID INTEGER,
    NAME VARCHAR(50),
    DEPARTMENT VARCHAR(50),
    SALARY INTEGER
);

INSERT INTO EMPLOYEES(ID, NAME, DEPARTMENT, SALARY) VALUES
    (1, 'Pat Fay', 'HR', 50000),
    (2, 'DONALD', 'IT', 60000),
    (3, 'STEVEN', 'SALES', 80000),
    (4, 'SUSAN', 'IT', 70000),
    (5, 'JENNIFER', 'MARKETING', 40000);

SELECT * FROM EMPLOYEES;

CREATE OR REPLACE VIEW IT_EMPLOYEES AS
SELECT ID,NAME,SALARY
FROM EMPLOYEES
WHERE DEPARTMENT = 'IT';

MYDB.MYSCHEMA.CUSTOMER_STAGE
SELECT * FROM IT_EMPLOYEES;

CREATE OR REPLACE MATERIALIZED VIEW HR_EMPLOYEES AS
SELECT ID,NAME,SALARY
FROM EMPLOYEES
WHERE DEPARTMENT = 'HR';

SELECT * FROM HR_EMPLOYEES;

CREATE OR REPLACE SECURE VIEW SALES_EMPLOYEES AS
SELECT ID,NAME,SALARY
FROM EMPLOYEES
WHERE DEPARTMENT = 'SALES';

SELECT * FROM SALES_EMPLOYEES;MYDB.MYSCHEMA.CUSTOMER_STAGE 